name: my work flow action
on: workflow_dispatch
jobs: 
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: Print hello world
        run: echo "hello world!"
      - name: Run a multi-line script
        run: |
          apt-get update
          apt-get upgrade -y
         
